apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
data:
  Corefile: |
    .:53 {
        errors
        health {
           lameduck 5s
        }
        ready
        hosts {
           10.0.0.200 proxy.k8s.local
           10.0.0.201 dns.k8s.local
           fallthrough
        }
        kubernetes cluster.local in-addr.arpa ip6.arpa {
           pods insecure
           fallthrough in-addr.arpa ip6.arpa
           ttl 30
        }
        prometheus :9153
        forward . /etc/resolv.conf {
           max_concurrent 1000
        }
        cache 30 {
           disable success cluster.local
           disable denial cluster.local
        }
        loop
        reload
        loadbalance
    }

    k8s.local:53 {
        errors
        hosts {
           10.0.0.201 dns.k8s.local
           fallthrough
        }
        cache 30
        etcd {
            path /skydns
            endpoint http://10.0.0.201:2379
        }
        loadbalance
    }
