apiVersion: v1
kind: ServiceAccount
metadata:
  name: homelab-admin
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: homelab-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: homelab-admin
    namespace: kube-system
---
apiVersion: v1
kind: Secret
metadata:
  name: homelab-admin
  namespace: kube-system
  annotations:
    kubernetes.io/service-account.name: homelab-admin
type: kubernetes.io/service-account-token
