repositories:
  - name: cilium
    url: https://helm.cilium.io

helmDefaults:
  createNamespace: false

## Document separator to satisfy Helmfile:
---
namespace: kube-system

releases:
  - name: cilium
    chart: cilium/cilium
    version: 1.17.4
    values:
      - values/values.yaml
