apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: default
  namespace: kube-system
spec:
  blocks:
  - cidr: 172.16.8.128/25
---
apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: default
  namespace: kube-system
spec:
  interfaces:
  - ^eth[0-9]+
  externalIPs: true
  loadBalancerIPs: true
