repositories:
- name: cilium
  url: https://helm.cilium.io

releases:
- name: cilium
  namespace: kube-system
  chart: cilium/cilium
  version: 1.16.3
  values:
  - k8sServiceHost: 172.16.8.0
  - k8sServicePort: 6443
  - kubeProxyReplacement: true
  - ingressController:
      enabled: true
      loadbalancerMode: shared
  - rollOutCiliumPods: true
  - k8sClientRateLimit:
      qps: 50
      burst: 100
  - l2announcements:
      enabled: true
  - externalIPs:
      enabled: true
  - hubble:
      enabled: true
      ui:
        enabled: true
      relay:
        enabled: true
