# Server configuration
server:
  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
      traefik.ingress.kubernetes.io/router.middlewares: traefik-redirect-https@kubernetescrd
    hostname: argocd.k8s.local
    tls: false

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

# Repository server
repoServer:
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

# Application controller
controller:
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 1Gi

# Redis
redis:
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

# Dex (disabled for dev environment)
dex:
  enabled: false

# Application Set Controller
applicationSet:
  enabled: true
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi

# Notifications Controller
notifications:
  enabled: true
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi

# Config management
configs:
  params:
    # Enable insecure mode for dev environment
    server.insecure: true
    # Disable TLS for simplicity in dev
    reposerver.disable.tls: true
    # Set the server URL
    server.url: https://argocd.k8s.local
  cm:
    # Server URL for UI redirects
    url: https://argocd.k8s.local
  repositories: {}
  secret:
    createSecret: true
