apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: monitoring
  namespace: argocd
spec:
  sourceRepos:
    - 'https://github.com/tier940/homelab'
  destinations:
    - namespace: 'argocd'
      server: '*'
    - namespace: 'kube-system'
      server: '*'
    - namespace: 'kubernetes-dashboard'
      server: '*'
    - namespace: 'kube-prometheus-stack'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
