repositories:
  - name: fluent
    url: https://fluent.github.io/helm-charts

helmDefaults:
  createNamespace: true

## Document separator to satisfy Helmfile:
---
namespace: kube-system

releases:
  - name: fluent-operator
    chart: fluent/fluent-operator
    version: 3.4.2
    values:
      - values/values.yaml
