apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

resources:
  - all/cluster-role.yaml
  - all/cluster-role-binding.yaml
  - all/service-account.yaml
  - all/deployment.yaml
