repositories:
  - name: cert-manager
    url: https://charts.jetstack.io/

helmDefaults:
  createNamespace: true

---
namespace: cert-manager

releases:
  - name: cert-manager
    chart: cert-manager/cert-manager
    version: 1.17.1
    values:
      - values.yaml
