---
genv:
  stage: dev
  env: a
  use_ipv6: false
  proxy:
    name: haproxy
    haproxy:
      version: "3.0.5-1.fc42.x86_64"
    traefik:
      version: "3.5.3"
  dns:
    coredns:
      version: "1.13.1"
    etcd:
      version: "3.6.5"
  kubernetes:
    kube_version: 1.34
    crio_version: 1.34
    high_availability: true
    kubeadm:
      kube_version: 1.34.1
      skip_phases: ["addon/kube-proxy"]
      networking:
        serviceSubnet: 100.96.0.0/16
        podSubnet: 100.244.0.0/20
