repositories:
  - name: cilium
    url: https://helm.cilium.io

releases:
  - name: cilium
    namespace: kube-system
    chart: cilium/cilium
    version: 1.17.1
    values:
      - debug:
          enabled: false
          verbose: flow
      - k8sServiceHost: 172.16.8.0
      - k8sServicePort: 6443
      - kubeProxyReplacement: true
      - ingressController:
          enabled: true
          loadbalancerMode: shared
      - prometheus:
          enabled: true
      - rollOutCiliumPods: true
      - resources:
        limits:
          cpu: 1000m
          memory: 1Gi
        requests:
          cpu: 200m
          memory: 512Mi
      - k8sClientRateLimit:
          qps: 50
          burst: 100
      - l2announcements:
          enabled: true
      - externalIPs:
          enabled: true
      - operator:
          rollOutPods: true
          prometheus:
            enabled: true
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 128Mi
      - hubble:
          enabled: false
          ui:
            enabled: false
            rollOutPods: false
          relay:
            enabled: false
            rollOutPods: false
