apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeshark

helmCharts:
  - name: kubeshark
    repo: https://helm.kubeshark.co/
    releaseName: kubeshark
    namespace: kubeshark
    version: "52.4"
    valuesFile: values.yaml
