apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applications
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/tier940/homelab.git
        revision: HEAD
        directories:
          - path: kubernetes/apps/*
  template:
    metadata:
      name: '{{ path.basename }}'
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: applications
      source:
        repoURL: https://github.com/tier940/homelab.git
        targetRevision: HEAD
        path: '{{ path }}'
      destination:
        name: in-cluster
        namespace: argocd
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
