apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: network
  namespace: argocd
  labels:
    dev.stonegarden: network
spec:
  generators:
    - git:
        repoURL: https://github.com/tier940/homelab
        revision: HEAD
        directories:
          - path: kubernetes/infra/network/*
  template:
    metadata:
      name: '{{ path.basename }}'
      labels:
        dev.stonegarden: network
    spec:
      project: network
      source:
        repoURL: https://github.com/tier940/homelab
        targetRevision: HEAD
        path: '{{ path }}'
      destination:
        name: in-cluster
        namespace: argocd
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
