# kube-prometheus-stack Development Environment Configuration

# Prometheus
prometheus:
  enabled: true
  prometheusSpec:
    replicas: 1
    retention: 7d
    retentionSize: "15GB"

    # Storage configuration
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: local-path
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 20Gi

    # ServiceMonitor auto-discovery
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false

    # Resources for development
    resources:
      requests:
        cpu: 200m
        memory: 1Gi
      limits:
        cpu: 2000m
        memory: 4Gi

# Grafana
grafana:
  enabled: true
  replicas: 1
  adminPassword: "admin" # Development environment

  # Data sources - disable default and configure manually
  sidecar:
    datasources:
      enabled: true
      defaultDatasourceEnabled: false

  additionalDataSources:
    - name: Prometheus
      type: prometheus
      uid: prometheus
      access: proxy
      url: http://kube-prometheus-stack-prometheus.kube-prometheus-stack.svc:9090
      isDefault: true
      jsonData:
        httpMethod: POST
        timeInterval: 30s
    - name: Jaeger
      type: jaeger
      uid: jaeger
      access: proxy
      url: http://jaeger-query.observability.svc:16686
      isDefault: false

  # Dashboards
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: "default"
          orgId: 1
          folder: ""
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/default

  dashboards:
    default:
      node-exporter:
        gnetId: 1860
        revision: 31
        datasource: Prometheus
      kubernetes-cluster:
        gnetId: 7249
        revision: 1
        datasource: Prometheus
      kubernetes-pods:
        gnetId: 6417
        revision: 1
        datasource: Prometheus
      cilium-metrics:
        gnetId: 16611
        revision: 1
        datasource: Prometheus

  # Ingress
  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - grafana.k8s.local

  # Resources
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

# AlertManager
alertmanager:
  enabled: true
  alertmanagerSpec:
    replicas: 1
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: local-path
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 5Gi

# node-exporter
nodeExporter:
  enabled: true

# kube-state-metrics
kubeStateMetrics:
  enabled: true

# kubelet
kubelet:
  enabled: true
  serviceMonitor:
    interval: 30s

# Prometheus Operator
prometheusOperator:
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
