name: Release Helm Charts

on:
  workflow_dispatch:
    inputs:
      chart_name:
        description: "Name of the Helm Chart"
        required: true

jobs:
  package-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Setup Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.12.3

    - name: Package Helm Chart
      id: package_chart
      run: |
        cd temp/application/bases
        helm package "${{ github.event.inputs.chart_name }}"
        mkdir -p charts
        mv "${{ github.event.inputs.chart_name }}"-*.tgz charts/

    - name: Clone Target Repo
      run: |
        # Clone the gh-pages branch of the target repository
        git clone --branch gh-pages https://github.com/tier940/homelab-helm-repo.git target-repo

    - name: Update Helm Repo Index
      run: |
        # Check if index.yaml exists in the target repo
        if [ -f target-repo/index.yaml ]; then
          echo "Updating existing Helm repo index."
          helm repo index charts --merge target-repo/index.yaml --url https://tier940.github.io/homelab-helm-repo/
        else
          echo "Creating new Helm repo index."
          helm repo index charts --url https://tier940.github.io/homelab-helm-repo/
        fi
        mv charts/index.yaml target-repo/

    - name: Publish Helm Chart
      run: |
        cd target-repo
        cp -r ../charts/* .
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add .
        git commit -m "Update Helm charts for ${{ github.event.inputs.chart_name }}"
        git push origin gh-pages
