name: Release Helm Charts

on:
  workflow_dispatch:
    inputs:
      chart_name:
        description: "Name of the Helm Chart"
        required: true

permissions:
  contents: write

jobs:
  package-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Setup Helm
      uses: azure/setup-helm@v4
      with:
        version: v3.12.3

    - name: Package Helm Chart
      id: package_chart
      run: |
        mkdir -p temp/charts
        helm package "temp/application/bases/${{ github.event.inputs.chart_name }}" -d temp/charts

    - name: Update Helm Repo Index
      run: |
        if [ -f temp/charts/index.yaml ]; then
          echo "Updating existing Helm repo index."
          helm repo index temp/charts --merge temp/charts/index.yaml --url https://tier940.github.io/homelab/temp/charts
        else
          echo "Creating new Helm repo index."
          helm repo index temp/charts --url https://tier940.github.io/homelab/temp/charts
        fi

    - name: Publish Helm Chart
      env:
        GITHUB_TOKEN: ${{ secrets.GHA_TOKEN }}
      run: |
        cd temp/charts
        git config --global user.email "tier940@protonmail.com"
        git config --global user.name "tier940"
        git add .
        git commit -m "Update Helm repo index with new chart: ${{ github.event.inputs.chart_name }}"
        git push origin gh-pages
